=== chfsx/ILIAS-migration/xml/ilias_lo.dtd
<!-- ilias_lo.dtd for creating ILIAS LearningObjects, see http://www.ilias.uni-koeln.de/download/dtd/ilias_lo.dtd for current version -->
<!-- initial version by Maik Stuehrenberg (Giessen University) for the BMBF-funded project MiLCA (Medienintensive Lehrmodule in der Computerlinguistik-Ausbildung), modelled after LOM version 1 Final Draft -->
<!-- modifications and adoption to ILIAS made by Maik Stuehrenberg (Giessen University), Martin Rus, Matthias Rulinski, Matthias Kunkel (ILIAS open source, University of Cologne), Sascha Hofmann (Databay AG, Aachen) -->
<!-- $id$ -->
<!-- language codes referring to ISO 639-1 Alpha-2 code, see http://www.oasis-open.org/cover/iso639a.html for details -->
<!ENTITY % langcode "none | aa | ab | af | am | ar | as | ay | az | ba | be | bg | bh | bi | bn | bo | br | ca | co | cs | cy | da | de | dz | el | en | eo | es | et | eu | fa | fi | fj | fo | fr | fy | ga | gd | gl | gn | gu | ha | he | hi | hr | hu | hy | ia | ie | ik | id | is | it | iu | ja | jv | ka | kk | kl | km | kn | ko | ks | ku | ky | la | ln | lo | lt | lv | mg | mi | mk | ml | mn | mo | mr | ms | mt | my | na | ne | nl | no | oc | om | or | pa | pl | ps | pt | qu | rm | rn | ro | ru | rw | sa | sd | sg | sh  | si | sk | sl | sm | sn | so | sq | sr | ss | st | su | sv | sw | ta | te | tg | th | ti | tk | tl | tn | to | tr | ts | tt | tw | ug | uk | ur | uz | vi | vo | wo | xh | yi | yo | za | zh | zu">
<!-- types of content -->
<!ENTITY % text "#PCDATA | Comment | Link | Emph | Strong | Quotation | Code | Formula | Annotation | List | Table | GlossaryTerm | Reference | RefTarget">
<!ENTITY % commenttext "#PCDATA | Link | Emph | Strong | Quotation | Code | Formula | Annotation | List | Table | GlossaryTerm | Reference | RefTarget">
<!ENTITY % reftext "#PCDATA | Comment | Link | Emph | Strong | Quotation | Code | Formula | Annotation | List | Table | GlossaryTerm | Reference">
<!ENTITY % linktext "#PCDATA | Comment | Emph | Strong | Quotation | Code | GlossaryTerm | Reference | RefTarget">
<!ENTITY % emphtext "#PCDATA | Comment | Link | Strong | Quotation | Code | Formula | List | GlossaryTerm | Reference | RefTarget">
<!ENTITY % strongtext "#PCDATA | Comment | Link | Emph | Quotation | Code | Formula | List | GlossaryTerm | Reference | RefTarget">
<!ENTITY % simpletext "#PCDATA | Link | Emph | Strong | Quotation | Code | Formula | GlossaryTerm | Reference | RefTarget">
<!ENTITY % titletext "#PCDATA | Emph | Strong | Quotation | Code | Formula">
<!-- technical entities -->
<!ENTITY % operatingsystem "#PCDATA | PC-DOS | MS-Windows | MacOS | Unix | Multi-OS | None">
<!ENTITY % browser "#PCDATA | Any | NetscapeCommunicator | MS-InternetExplorer | Opera | Amaya | Mozilla">
<!-- LearningObject: object of highest complexity -->
<!-- if the LearningObject has an AggregationLevel 1 (atomic), there is only MetaData and optionally Layout -->
<!ELEMENT LearningObject (MetaData, Layout?, Content?, Test?, Glossary?, Bibliography?)>
<!-- METADATA -->
<!-- MetaData referring to LOM/SCORM standard, see http://www.adlnet.org/library/documents/scorm/specifications/SCORM_1.2_CAM.pdf for details -->
<!-- the base scheme consists of nine categories: -->
<!-- Relation and Classification can be used more than once in EducationalUnits but is useless in most of LearningObjects -->
<!ELEMENT MetaData (General, Lifecycle?, Meta-Metadata?, Technical?, Educational?, Rights?, Relation*, Annotation*, Classification*)>
<!-- 1 General information about the resource as a whole -->
<!ELEMENT General (Identifier+, Title, Language+, Description+, Keyword+, Coverage*)>
<!ATTLIST General
	Structure (Atomic | Collection | Networked | Hierarchical | Linear) #REQUIRED
	AggregationLevel (1 | 2 | 3 | 4) #REQUIRED
>
<!-- AggregationLevel 1 = smallest level of aggregation, e.g. raw media data or fragments -->
<!-- AggregationLevel 2 = a collection of atoms, e.g. an HTML document with some embedded pictures -->
<!-- AggregationLevel 3 = a collection of level 2 learning objects, e.g. a web of HTML documents, with an index page that links the pages together of a course -->
<!-- AggregationLevel 4 = the largest level of aggregation, e.g. a set of courses that lead to a certificate -->
<!-- AggregationLevel 1 should be used for images and other media embedded in another LO -->
<!-- AggregationLevel 4 should be used only within ILIAS course management system! -->
<!-- 1.1 A global unique label, that identifies this learning object -->
<!ELEMENT Identifier EMPTY>
<!ATTLIST Identifier
	Catalog CDATA #IMPLIED
	Entry ID #REQUIRED
>
<!-- 1.2 Name given to this resource-->
<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title
	Language (%langcode;) #REQUIRED
>
<!-- 1.3 The primary human language used within this resource to communicate to the intended user-->
<!ELEMENT Language (#PCDATA)>
<!-- 1.4 A textual description of the content of this resource being described -->
<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description
	Language (%langcode;) #REQUIRED
>
<!-- 1.5 Keywords or phrases describing this resource -->
<!ELEMENT Keyword (#PCDATA)>
<!ATTLIST Keyword
	Language (%langcode;) #REQUIRED
>
<!-- 1.6 The span or extent of such things as time, culture, geography or region that applies to this resource -->
<!ELEMENT Coverage (#PCDATA)>
<!ATTLIST Coverage
	Language (%langcode;) #REQUIRED
>
<!-- 2. History and current state of the resource and those who have affected this resource during its evolution -->
<!-- Contribute: (Creator | Validator) are NOT valid Role attributes! -->
<!ELEMENT Lifecycle (Version, Contribute+)>
<!ATTLIST Lifecycle
	Status (Draft | Final | Revised | Unavailable) #REQUIRED
>
<!--2.1 The edition of this resource -->
<!ELEMENT Version (#PCDATA)>
<!ATTLIST Version
	Language (%langcode;) #REQUIRED
>
<!-- 2.3 This sub-category describes those people or organization that have affected the state of this resource during its evolution-->
<!ELEMENT Contribute (Entity+, Date)>
<!ATTLIST Contribute
	Role (Author | Publisher | Unknown | Initiator | Terminator | Editor | GraphicalDesigner | TechnicalImplementer | ContentProvider | TechnicalValidator | EducationalValidator | ScriptWriter | InstructionalDesigner | SubjectMatterExpert | Creator | Validator) #REQUIRED
>
<!-- 2.3.2 The identification of and information about the people or organizations contributing to this resource, most relevant first-->
<!-- LOM standard proposed Entity (#PCDATA | vCard). Support for vCards will be added later. First goal is to keep database structure simple to get it to work :-) shofmann 2002-25-10 -->
<!ELEMENT Entity (#PCDATA | Entity)*>
<!-- 2.3.3 This sub-category defines the date of the contribution-->
<!ELEMENT Date (#PCDATA)>
<!-- 3. Specific information about the meta-data record itself -->
<!-- Contribute: Only (Creator | Validator) are valid Role attributes! -->
<!ELEMENT Meta-Metadata (Identifier+, Contribute+)>
<!ATTLIST Meta-Metadata
	MetadataScheme CDATA #FIXED "LOM v 1.0"
	Language (%langcode;) #IMPLIED
>
<!-- 4. Technical requirements and characteristics of the resource -->
<!ELEMENT Technical (Size?, Location*, (Requirement* | OrComposite*)?, InstallationRemarks?, OtherPlatformRequirements?, Duration?)>
<!ATTLIST Technical
	Format (application-x-authorware-bin | application-x-authorware-map | application-x-authorware-seg | application-andrew-inset | application-excel | application-hstu | application-mac-binhex40 | application-mac-compactpro | application-msword | application-octet-stream | application-oda | application-pdf | application-postscript | application-powerpoint | application-rtf | application-smil | application-vnd.mif | application-vnd.ms-powerpoint | application-x-bcpio | application-x-cdlink | application-x-chess-pgn | application-x-compress | application-x-cpio | application-x-csh | application-x-director | application-x-dvi | application-x-futuresplash | application-x-gtar | application-x-gzip | application-x-hdf | application-x-httpd-cgi | application-x-javascript | application-x-koan | application-x-latex | application-x-mif | application-x-netcdf | application-x-sh | application-x-shar | application-x-shockwave-flash | application-x-stuffit | application-x-sv4cpio | application-x-sv4crc | application-x-tar | application-x-tcl | application-x-tex | application-x-texinfo | application-x-troff | application-x-troff-man | application-x-troff-me | application-x-troff-ms | application-x-ustar | application-x-wais-source | application-zip | audio-basic | audio-midi | audio-mpeg | audio-x-aiff | audio-x-pn-realaudio | audio-x-pn-realaudio-plugin | audio-x-realaudio | audio-x-wav | chemical-x-pdb | image-bmp | image-fif | image-gif | image-ief | image-jpeg | image-pict | image-png | image-tiff | image-x-cmu-raster | image-x-freehand | image-x-portable-anymap | image-x-portable-bitmap | image-x-portable-graymap | image-x-portable-pixmap | image-x-rgb | image-x-xbitmap | image-x-xpixmap | image-x-xwindowdump | model-iges | model-mesh | model-vrml | text-css | text-html | text-plain | text-richtext | text-sgml | text-tab-separated-values | text-x-setext | text-x-sgml | text-xml | video-mpeg | video-quicktime | video-x-msvideo | video-x-sgi-movie | x-conference-x-cooltalk | x-world-x-vrml) #REQUIRED
>
<!-- 4.2 The size of the digital resource in bytes. Only the digits '0'..'9' should be used; the unit is bytes, not MBytes,GB,etc.-->
<!ELEMENT Size (#PCDATA)>
<!-- 4.3 A string that is used to access this resource, see LOM annotation-->
<!ELEMENT Location (#PCDATA)>
<!-- 4.4 Grouping of multiple requirements -->
<!-- 4.4.1 Defining attributes of OrComposite -->
<!-- This sub-category describes the technical capabilities required in order to use this resource -->
<!ELEMENT OrComposite (Requirement+)>
<!ELEMENT Requirement (Type)>
<!ELEMENT Type (OperatingSystem | Browser)>
<!ELEMENT OperatingSystem EMPTY>
<!ATTLIST OperatingSystem
	Name (%operatingsystem;) #REQUIRED
	MinimumVersion CDATA #IMPLIED
	MaximumVersion CDATA #IMPLIED
>
<!ELEMENT Browser EMPTY>
<!ATTLIST Browser
	Name (%browser;) #REQUIRED
	MinimumVersion CDATA #IMPLIED
	MaximumVersion CDATA #IMPLIED
>
<!-- 4.5 Description on how to install this resource-->
<!ELEMENT InstallationRemarks (#PCDATA)>
<!ATTLIST InstallationRemarks
	Language (%langcode;) #REQUIRED
>
<!-- 4.6 Information about other software and hrdware requirements -->
<!ELEMENT OtherPlatformRequirements (#PCDATA)>
<!ATTLIST OtherPlatformRequirements
	Language (%langcode;) #REQUIRED
>
<!-- 4.7 Time continuous resource takes when  -->
<!ELEMENT Duration (#PCDATA)>
<!-- 5. Key educational or pedagogic characteristics of the resource -->
<!ELEMENT Educational (TypicalAgeRange, TypicalLearningTime, Description*)>
<!ATTLIST Educational
	InteractivityType (Active | Expositive | Mixed) #REQUIRED
	LearningResourceType (Exercise | Simulation | Questionnaire | Diagram | Figure | Graph | Index | Slide | Table | NarrativeText | Exam | Experiment | ProblemStatement | SelfAssessment | Lecture) #REQUIRED
	InteractivityLevel (VeryLow | Low | Medium | High | VeryHigh) #REQUIRED
	SemanticDensity (VeryLow | Low | Medium | High | VeryHigh) #REQUIRED
	IntendedEndUserRole (Teacher | Author | Learner | Manager) #REQUIRED
	Context (School | HigherEducation | Training | Other) #REQUIRED
	Difficulty (VeryEasy | Easy | Medium | Difficult | VeryDifficult) #REQUIRED
>
<!-- 5.7 Age of the typical intended user-->
<!ELEMENT TypicalAgeRange (#PCDATA)>
<!ATTLIST TypicalAgeRange
	Language (%langcode;) #REQUIRED
>
<!-- 5.9 Approximate or typical time it takes to work with this resource-->
<!ELEMENT TypicalLearningTime (#PCDATA)>
<!-- 6. Intellectual property rights and conditions of use for this resource -->
<!ELEMENT Rights (Description)>
<!ATTLIST Rights
	Cost (Yes | No) #REQUIRED
	CopyrightAndOtherRestrictions (Yes | No) #REQUIRED
>
<!-- 7. Relationship between this resource and other resources, if any -->
<!ELEMENT Relation (Resource)>
<!ATTLIST Relation
	Kind (IsPartOf | HasPart | IsVersionOf | HasVersion | IsFormatOf | HasFormat | References | IsReferencedBy | IsBasedOn | IsBasisFor | Requires | IsRequiredBy) #REQUIRED
>
<!-- 7.2  The target resource that this relationship references-->
<!-- the Identifier should be of type IDREF cause its value is a reference -->
<!-- using the XML IDREF stating the CatalogEntry is obsolete (the CatalogEntry information could be retrieved with XSLT) -->
<!ELEMENT Resource (Identifier_+, Description+)>
<!-- 7.2.1 A globally unique label, that identifies the target learning object-->
<!ELEMENT Identifier_ EMPTY>
<!ATTLIST Identifier_
	Catalog CDATA #IMPLIED
	Entry IDREF #IMPLIED
>
<!-- 8. Comments on the educational use of this resource-->
<!ELEMENT Annotation (Entity, Date, Description)>
<!-- 9. Description where this resource is placed within a particular classification system-->
<!ELEMENT Classification (TaxonPath+, Description, Keyword+)>
<!ATTLIST Classification
	Purpose (Discipline | Idea | Prerequisite | EducationalObjective | AccessibilityRestrictions | EducationalLevel | SkillLevel | SecurityLevel | Competency) #REQUIRED
>
<!-- 9.2 This sub-category describes a taxonomic path in a specified classification system. see LOM-->
<!ELEMENT TaxonPath (Source, Taxon+)>
<!-- 9.2.1 The name of the classification system-->
<!ELEMENT Source (#PCDATA)>
<!ATTLIST Source
	Language (%langcode;) #REQUIRED
>
<!-- 9.2.2 -->
<!ELEMENT Taxon (#PCDATA)>
<!ATTLIST Taxon
	Language (%langcode;) #REQUIRED
	Id ID #IMPLIED
>
<!-- LAYOUT -->
<!-- Layout information for formatting content output -->
<!ELEMENT Layout EMPTY>
<!ATTLIST Layout
	KeepWithPrevious (Yes | No) #IMPLIED
	KeepWithNext (Yes | No) #IMPLIED
	CSS-URL CDATA #IMPLIED
	HorizontalAlign (Left | Center | Right) #IMPLIED
	VerticalAlign (Top | Middle | Bottom) #IMPLIED
	TargetFrame (Media | FAQ | Glossary) #IMPLIED
>
<!--  CONTENT -->
<!-- (textual) Content of a learning object should be divided in single paragraphs -->
<!-- the Content may include another LO (e.g. images, video) -->
<!-- LO which contain other LOs should use AggregationLevel 2 or 3 -->
<!ELEMENT Content (Text | LearningObject)+>
<!ELEMENT Text (Headline?, Paragraph+)+>
<!ELEMENT Paragraph (%text;)*>
<!ATTLIST Paragraph
	Language (%langcode;) #REQUIRED
	Characteristic (Example | Citation | Mnemonic) #IMPLIED
>
<!-- headline is not a title of a resource but a special type of markup for a text -->
<!ELEMENT Headline (%titletext;)*>
<!ATTLIST Headline
	Language (%langcode;) #REQUIRED
>
<!ELEMENT Comment (%commenttext;)*>
<!ATTLIST Comment
	Language (%langcode;) #REQUIRED
>
<!-- a Link element to link to _external_ resources -->
<!-- it is fixed to xlink-type simple, only required attribute value is href -->
<!ELEMENT Link (%linktext;)*>
<!ATTLIST Link
	Href CDATA #REQUIRED
	Title CDATA #IMPLIED
>
<!ELEMENT Emph (%emphtext;)*>
<!ATTLIST Emph
	Reason (Keyword | Intuition | MetaLanguageUse) #IMPLIED
>
<!ELEMENT Strong (%strongtext;)*>
<!ATTLIST Strong
	Reason (Keyword | Intuition | MetaLanguageUse) #IMPLIED
>
<!ELEMENT Quotation (%text;)*>
<!ATTLIST Quotation
	Language (%langcode;) #REQUIRED
	Reference IDREF #IMPLIED
>
<!ELEMENT Code (#PCDATA)>
<!ATTLIST Code
	Id ID #REQUIRED
	ProgrammingLanguage CDATA #IMPLIED
>
<!ELEMENT Formula (#PCDATA)>
<!ATTLIST Formula
	Id ID #REQUIRED
>
<!ELEMENT Markup (%text;)*>
<!ATTLIST Markup
	Type CDATA #REQUIRED
	Attribute_1 CDATA #IMPLIED
	Attribute_2 CDATA #IMPLIED
	Attribute_3 CDATA #IMPLIED
	Attribute_4 CDATA #IMPLIED
	Attribute_5 CDATA #IMPLIED
>
<!ELEMENT List (Title?, Item+)>
<!ATTLIST List
	Type (Ordered | Unordered) #REQUIRED
>
<!ELEMENT Item (Paragraph+)>
<!-- table model is some kind of a mixture of mimalized CALS and HTML dtd -->
<!-- only a minimum of style elements and attributes defined -->
<!ELEMENT Table (Title?, HeaderCaption?, FooterCaption?, Summary?, TableRow+)>
<!ATTLIST Table
	Id ID #IMPLIED
	Width CDATA #IMPLIED
	Height CDATA #IMPLIED
	Border CDATA #IMPLIED
>
<!ELEMENT HeaderCaption (%titletext;)*>
<!ELEMENT FooterCaption (%titletext;)*>
<!ELEMENT Summary (%simpletext;)*>
<!ATTLIST Summary
	Language (%langcode;) #IMPLIED
>
<!ELEMENT TableRow (TableData+)>
<!ELEMENT TableData (%text;)*>
<!ATTLIST TableData
	Colspan CDATA #IMPLIED
	Rowspan CDATA #IMPLIED
>
<!-- a Reference element to refer to _internal_ resources via XML ID/IDREF -->
<!-- each LO has an Identifier attribute (type ID) in its Metadata/General element -->
<!-- only this one should be used! -->
<!-- other less usable Identifier attributes are in Metadata/Meta-Metadata and in Metadata/Resource element -->
<!-- they should be ignored! -->
<!-- in case of RefTarget the concerning attribute Id of the RefTarget should be used! -->
<!ELEMENT Reference (%reftext;)*>
<!ATTLIST Reference
	Reference_to IDREF #REQUIRED
	Type (LearningObject | Test | TestItem | Glossary | GlossaryItem | Bibliography | RefTarget) #REQUIRED
>
<!ELEMENT RefTarget (%reftext;)*>
<!ATTLIST RefTarget
	Id ID #REQUIRED
>
<!-- TEST -->
<!ELEMENT Test (TestItem+)>
<!ATTLIST Test
	Id ID #IMPLIED
>
<!ELEMENT TestItem (Question, Answer+, Hint*)>
<!ATTLIST TestItem
	Id ID #IMPLIED
>
<!ELEMENT Question (Paragraph | LearningObject)+>
<!ELEMENT Answer (Paragraph | LearningObject)+>
<!ELEMENT Hint (Paragraph | LearningObject)+>
<!-- GLOSSARY -->
<!ELEMENT Glossary (GlossaryItem+)>
<!ATTLIST Glossary
	Id ID #IMPLIED
>
<!ELEMENT GlossaryItem (GlossaryTerm, (Definition* | DefinitionList?))>
<!ATTLIST GlossaryItem
	Id ID #IMPLIED
>
<!ELEMENT GlossaryTerm (%titletext;)*>
<!ATTLIST GlossaryTerm
	Definition IDREF #REQUIRED
>
<!ELEMENT Definition (Paragraph+)>
<!ATTLIST Definition
	Id ID #REQUIRED
>
<!ELEMENT DefinitionList (Definition+)>
<!ATTLIST DefinitionList
	Id ID #REQUIRED
>
<!-- BIBLIOGRAPHY -->
<!-- will be extended later -->
<!ELEMENT Bibliography (#PCDATA)>
<!ATTLIST Bibliography
	Id ID #IMPLIED
>

=== chfsx/ILIAS-migration/xml/A-1-2.xml
<?xml version="1.0"?>
<!DOCTYPE LearningObject SYSTEM "\\Salomon\kain\ILIAS_OS\Dokumentation ILIAS\XML\ILIAS DTD\Test\ilias_lo.dtd">
<LearningObject><MetaData><General AggregationLevel="2" Structure="Collection"><Identifier Catalog="ILIAS" Entry="A-1-2"/><Title Language="de"><Strong>Testdokument	- Teil 2</Strong></Title><Language>Deutsch</Language><Description Language="de">Testdokument zum <Emph>Überprüfen</Emph> des LO-Imports in ILIAS</Description><Keyword Language="de">Test,Import, ILIAS</Keyword><Coverage Language="de">Hochschule</Coverage></General><Lifecycle Status="Draft"><Version Language="de">1.0</Version><Contribute Role="Author"><Entity>Matthias Kunkel</Entity><Entity>keine Ahnung</Entity><Date>2002-11-25</Date></Contribute></Lifecycle><Meta-Metadata><Identifier Catalog="ILIAS" Entry="ILIAS123"/><Contribute Role="Author"><Entity>noch was zum Eintragen</Entity><Date>2002-10-20</Date></Contribute></Meta-Metadata><Technical Format="text-plain"><Requirement><Type><Browser Name="NetscapeCommunicator" MinimumVersion="3.0"/></Type></Requirement></Technical><Educational InteractivityType="Mixed" LearningResourceType="NarrativeText" InteractivityLevel="Medium" SemanticDensity="Low" IntendedEndUserRole="Learner" Context="Training" Difficulty="Easy"><TypicalAgeRange Language="de">18-65</TypicalAgeRange><TypicalLearningTime>1 Stunde</TypicalLearningTime><Language>Deutsch</Language></Educational><Classification Purpose="EducationalLevel"><TaxonPath><Source Language="de">ISBN</Source><Taxon><Entry>123.234.345</Entry></Taxon></TaxonPath><Description Language="de">Irgendwas</Description><Keyword Language="de">Sonstwo</Keyword></Classification></MetaData><Content><Text><Headline Language="de">Über ILIAS</Headline><Paragraph Language="de">Die Online-Lernplattform ILIAS (Integriertes Lern-, Informations- und ArbeitskooperationsSystem) steht als open source Software unter der General Public Licence (GPL) zur Verfügung. Damit können Hochschulen, Bildungseinrichtungen und andere Interessenten das System kostenlos nutzen und nach eigenen Vorstellungen weiterentwickeln.</Paragraph><Paragraph Language="de">

ILIAS wurde im Rahmen des VIRTUS-Projekts an der Wirtschafts- und Sozialwissenschaftlichen Fakultät der Universität zu Köln entwickelt. Mittels einer Client-Server-System ermöglicht ILIAS das Erstellen, Bearbeiten und Darstellen von Lehrmaterialien in einer einheitlichen Umgebung.

</Paragraph><Paragraph Language="de">Zu den umfangreichen Features von ILIAS gehören:<List Type="Unordered"><Item><Paragraph Language="de">Persönlicher Schreibtisch</Paragraph></Item><Item><Paragraph Language="de">Lernumgebung</Paragraph></Item><Item><Paragraph Language="de">Arbeitsumgebung</Paragraph></Item><Item><Paragraph Language="de">Kommunikationstools</Paragraph></Item></List><List Type="Unordered"><Item><Paragraph Language="de">Gruppen- und Rechtesystem</Paragraph></Item></List></Paragraph></Text><Text><Paragraph Language="de">Auf diesen Seiten hier erhalten Sie die neuesten Versionen, Module und Informationen. Das aktuelle Release können Sie sich auf der <Link Href="http://www.ilias.uni-koeln.de/source.html" Title="Sourcecode">source-Seite</Link> herunterladen. Unter info finden Sie wichtige Informationen und Neuigkeiten. Und auf der <Link Href="http://www.ilias.uni-koeln.de/docs.html" Title="Dokumente">docs-Seite</Link> werden wir alle Dokumentationen zu ILIAS bereitstellen. Einen ersten Eindruck von ILIAS bekommen Sie in unserem <Link Href="http://www.ilias.uni-koeln.de/demo" Title="Demo-Installation">demo-System</Link>. An der Uni Köln koordiniert ein Team die Softwareentwicklung und ist zugleich Ansprechpartner für alle externen Entwickler. </Paragraph></Text><LearningObject><MetaData><General Structure="Atomic" AggregationLevel="1"><Identifier Catalog="ILIAS" Entry="A-1-1-1"/><Title Language="de">CampusSource</Title><Language>de</Language><Description Language="de">CampusSource Logo</Description><Keyword Language="de">CampusSource</Keyword></General><Technical Format="image-gif"><Location>http://www.ilias.uni-koeln.de/ios/lgs/ilias.gif</Location><Requirement><Type><Browser Name="Any" MinimumVersion="3.0"/></Type></Requirement><Duration>1"</Duration></Technical></MetaData><Layout KeepWithNext="Yes" KeepWithPrevious="No"/></LearningObject><Text><Paragraph Language="de">ILIAS ist Teil der NRW-Initiative CampusSource und steht nach abgeschlossener Zertifizierung auch in der Softwarebörse von CampusSource zum Download zur Verfügung.
</Paragraph></Text></Content><Bibliography>Kunkel, Matthias: Erste Schritte mit ILIAS; 22. Auflage, Köln, 2002</Bibliography></LearningObject>
